services:
  wem-dev:
    container_name: wem-dev
    build: .
    restart: unless-stopped
    depends_on:
      - db-dev
      - redis-dev
    env_file: .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db-dev
      DB_PORT: 3306
      DB_DATABASE: wem
      DB_USERNAME: wem_user
      DB_PASSWORD: password
      REDIS_HOST: redis-dev
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
    expose:
      - "9000"
    command: ["/entrypoint.sh"]

  nginx:
    container_name: wem-nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - wem-dev
    ports:
      - "45060:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db-dev:
    container_name: db-dev
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wem
      MYSQL_ROOT_PASSWORD: wemdev
      MYSQL_USER: wem_user
      MYSQL_PASSWORD: password
    volumes:
      - db-dev_data:/var/lib/mysql

  redis-dev:
    container_name: redis-dev
    image: redis:alpine
    ports:
      - "6379:6379"

  laravel-echo-server:
    container_name: laravel-echo-server
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: "npm run echo-server"
    depends_on:
      - wem-dev
    ports:
      - "6001:6001"

volumes:
  db-dev_data:
